ethereum_rpc = ""
drosera_rpc = ""
drosera_address = ""

[traps]

[traps.gasprice]
path = "out/GasGuard.sol/GasGuard.json"
response_contract = "0x66847043dA36DE12D536054A11F3364E386bb7bc"
response_function = "setMaxGasWei(uint256)"
cooldown_period_blocks = 15
min_number_of_operators = 1
max_number_of_operators = 1
block_sample_size = 1
private_trap = false
whitelist = []
address = "0x66847043dA36DE12D536054A11F3364E386bb7bc"
